In [4]:
import pandas as pd
import numpy as np
from sklearn import metrics
from functions import TransformColumn, DropColumn, MinMaxFunc, cleanDF, NormalizedDF
from functionsСlassification import KmeansFunc, OneHotFunc

In [5]:
#Имена полей
names = ['Partner','EI','CoefSR','AreaOfActivity','CoopTime','CalculationObject','OverduePayment','SalesDebt','DelayDays','ClientDebt']
group_column_name = ['Partner','EI','Coef-SR','AreaOfActivity','CoopTime','DocCount','DocAvg','DocDelayAvg','DocDelayCount','DocRatioOfDelayed']
#Загрузка полей
dataf = pd.read_excel('1.xlsx', names=names)
dataftest = pd.read_excel('2.xlsx', names=names)

In [6]:
dataf

,Partner,EI,CoefSR,AreaOfActivity,CoopTime,CalculationObject,OverduePayment,SalesDebt,DelayDays,ClientDebt
0,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-021008 от 22.1...,1.0,1.030270e+03,6.0,NaN
1,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-021889 от 30.1...,NaN,2.016420e+03,NaN,NaN
2,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-000101 от 06.0...,NaN,1.242200e+03,NaN,NaN
3,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-000793 от 19.0...,1.0,1.132710e+03,6.0,NaN
4,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-000902 от 20.0...,NaN,1.647500e+03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
336786,ЦБ-ЦБ021605,Физическое лицо,0.75,1 — Город,6.0,Реализация товаров и услуг Ч9ЦБ-014481 от 30.1...,NaN,NaN,NaN,4.273200e+03
336787,ЦБ-ЦБ021606,Физическое лицо,0.75,1 — Город,6.0,Реализация товаров и услуг Ч9ЦБ-014285 от 29.1...,NaN,NaN,NaN,2.022460e+04
336788,ЦБ-ЦБ021613,Физическое лицо,NaN,1 — Город,NaN,Реализация товаров и услуг Ч4ЦБ-035522 от 29.1...,1.0,1.407400e+02,2.0,1.407400e+02
336789,ЦБ-ЦБ021617,Физическое лицо,NaN,1 — Город,NaN,Реализация товаров и услуг Ч6ЦБ-015031 от 30.1...,1.0,7.012000e+02,1.0,7.012000e+02
336790,Итого,NaN,NaN,NaN,NaN,NaN,108038.0,2.063234e+09,4.0,1.361570e+08

In [7]:
dataftest

,Partner,EI,CoefSR,AreaOfActivity,CoopTime,CalculationObject,OverduePayment,SalesDebt,DelayDays,ClientDebt
0,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-034269 от 21.1...,NaN,1.874580e+03,NaN,NaN
1,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-035219 от 29.1...,NaN,1.740540e+03,NaN,NaN
2,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-000741 от 18.0...,1.0,1.291470e+03,6.0,NaN
3,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-003017 от 15.0...,NaN,1.435560e+03,NaN,NaN
4,00-00000022,Физическое лицо,0.75,1 — Город,26.0,Реализация товаров и услуг Ч4ЦБ-004606 от 02.0...,NaN,1.317060e+03,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
141431,ЦБ-ЦБ022490,Физическое лицо,0.25,1 — Город,1.0,Реализация товаров и услуг Ч9ЦБ-027771 от 31.0...,NaN,NaN,NaN,7.206000e+02
141432,ЦБ-ЦБ022491,Физическое лицо,0.75,1 — Город,1.0,Реализация товаров и услуг Ч4ЦБ-014009 от 31.0...,NaN,NaN,NaN,7.206000e+02
141433,ЦБ-ЦБ022495,Физическое лицо,0.25,1 — Город,1.0,Реализация товаров и услуг Ч9ЦБ-027765 от 31.0...,NaN,NaN,NaN,2.280100e+03
141434,ЦБ-ЦБ022498,Физическое лицо,0.25,2 — Область,1.0,Реализация товаров и услуг Ч9ЦБ-027732 от 31.0...,NaN,NaN,NaN,1.532700e+03
141435,Итого,NaN,NaN,NaN,NaN,NaN,50446.0,8.116330e+08,3.0,1.434893e+08

In [8]:
#Удаление и предобразование обучаего набора данных
df = cleanDF(dataf)
dfNorm = NormalizedDF(df)
dfNorm = dfNorm.round(decimals = 4)
dfKmean = KmeansFunc(dfNorm)
dfCategory = dfKmean[['Partner', 'CategoryOfPartner']]
dfCategory = dfCategory.groupby(by=['Partner'], as_index=False)['CategoryOfPartner'].max()
dfFinal = OneHotFunc(dfKmean)
dfFinal = dfFinal.join(dfKmean[['EI','CoefSR','CoopTime','SalesDebt','DocDelayAvgNorm','DocRatioOfDelayed','DocDelay']])

In [9]:
dfFinal

,Risk_0,Risk_1,Risk_2,Risk_3,Risk_4,Risk_5,Risk_6,Risk_7,Risk_8,Risk_9,Risk_10,EI,CoefSR,CoopTime,SalesDebt,DocDelayAvgNorm,DocRatioOfDelayed,DocDelay
0,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1030.27,0.0146,0.6042,1
1,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,2016.42,0.0146,0.6042,0
2,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1242.20,0.0146,0.6042,0
3,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1132.71,0.0146,0.6042,1
4,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1647.50,0.0146,0.6042,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277605,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,2797.32,0.0053,1.0000,1
277606,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,12953.32,0.0079,0.5000,1
277607,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,5454.89,0.0079,0.5000,0
277608,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,11672.31,0.0053,1.0000,1
277609,0,0,0,0,0,0,0,1,0,0,0,1,0.00,0.0,1176.90,0.0211,1.0000,1

In [10]:
#Удаление и предобразование тестового набора данных
testdf = cleanDF(dataftest)
testdfNorm = NormalizedDF(testdf)
testdfNorm = testdfNorm.round(decimals = 4)
testdfNorm['CategoryOfPartner'] = 0
testdfCategory = testdfNorm[['Partner', 'CategoryOfPartner']]
for i in range(testdfCategory.shape[0]):
    df2 = dfCategory
    value = ''
    df3 = ''
    value = testdfCategory.at[i,'Partner']
    df3 = df2.loc[df2['Partner'] == value]
    if df3.size != 0:
        testdfCategory.loc[i,'CategoryOfPartner'] = df3['CategoryOfPartner'].values[0]
    else:
        testdfCategory = testdfCategory.drop(index = i)
        testdfNorm = testdfNorm.drop(index = i)
testdfCategory.reset_index(drop=True, inplace=True)
testdfNorm.reset_index(drop=True, inplace=True)
testdfFinal = OneHotFunc(testdfCategory)
testdfFinal = testdfFinal.join(testdfNorm[['EI','CoefSR','CoopTime','SalesDebt','DocDelayAvgNorm','DocRatioOfDelayed','DocDelay']])

In [11]:
#Запись тестового набора в файл
dftest = testdfCategory.join(testdfNorm[['EI','CoefSR','CoopTime','SalesDebt','DocDelayAvgNorm','DocRatioOfDelayed','DocDelay']])
writer = pd.ExcelWriter('CleanTest2.xlsx')
dftest.to_excel(writer)
writer.save()
writer = pd.ExcelWriter('CleanTest.xlsx')
testdfFinal.to_excel(writer)
writer.save()

In [12]:
testdfFinal

,Risk_0,Risk_1,Risk_2,Risk_3,Risk_4,Risk_5,Risk_6,Risk_7,Risk_8,Risk_9,Risk_10,EI,CoefSR,CoopTime,SalesDebt,DocDelayAvgNorm,DocRatioOfDelayed,DocDelay
0,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1874.58,0.0072,0.1429,0
1,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1740.54,0.0072,0.1429,0
2,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1291.47,0.0072,0.1429,1
3,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1435.56,0.0072,0.1429,0
4,0,0,0,0,1,0,0,0,0,0,0,1,0.75,26.0,1317.06,0.0072,0.1429,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103566,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,8930.50,0.0101,0.4000,0
103567,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,6603.23,0.0084,0.3333,1
103568,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,4007.40,0.0084,0.3333,0
103569,1,0,0,0,0,0,0,0,0,0,0,1,0.75,6.0,3938.97,0.0084,0.3333,0
103570,0,0,0,0,0,0,0,1,0,0,0,1,0.00,0.0,1157.20,0.0000,0.0000,0

In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [14]:
X = pd.DataFrame(dfFinal, columns = dfFinal.columns[:-1])
y = pd.DataFrame(dfFinal, columns = dfFinal.columns[-1:])
Xt = pd.DataFrame(testdfFinal, columns = testdfFinal.columns[:-1])
yt = pd.DataFrame(testdfFinal, columns = testdfFinal.columns[-1:])

In [15]:
tree = DecisionTreeClassifier(criterion='entropy', max_depth = 5).fit(X,y)
print(tree.score(Xt,yt))
print(classification_report(yt, tree.predict(Xt)))
print(confusion_matrix(yt, tree.predict(Xt)))

0.7815604754226569
              precision    recall  f1-score   support

           0       0.80      0.86      0.83     64787
           1       0.74      0.65      0.69     38784

    accuracy                           0.78    103571
   macro avg       0.77      0.75      0.76    103571
weighted avg       0.78      0.78      0.78    103571

[[55788  8999]
 [13625 25159]]

In [16]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(X,y)
print(model.score(Xt,yt))
print(classification_report(yt, model.predict(Xt)))
print(confusion_matrix(yt, model.predict(Xt)))

c:\Program Files\Python310\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7805659885489181
              precision    recall  f1-score   support

           0       0.80      0.87      0.83     64787
           1       0.75      0.63      0.68     38784

    accuracy                           0.78    103571
   macro avg       0.77      0.75      0.76    103571
weighted avg       0.78      0.78      0.78    103571

[[56517  8270]
 [14457 24327]]

In [17]:
from sklearn.tree import export_graphviz
export_graphviz(
            tree,
            out_file = "myTreeName.dot",
            feature_names = list(X.columns),
            class_names = ['BAD','OK'],
            filled = True,
            rounded = True)